### ISSUE TITLE
AttributeError: module 'signal' has no attribute 'SIGALRM'

### ISSUE THREAD

**Issue by Ohay-Angah** [deep-symbolic-mathematics/TPSR#2]
Thanks for your great work.

When running the run.sh or run.py, I got an attribute error while it was rescaling the expression: `refined_candidate[0]["predicted_tree"] =  scaler.rescale_function(env, refined_candidate[0]["predicted_tree"], *scale_params[0])`

```
Traceback (most recent call last):
  File "D:\xx\Anaconda\envs\deeplearning39\lib\site-packages\IPython\core\interactiveshell.py", line 3526, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-60ea49bf5158>", line 2, in <module>
    scaler.rescale_function(env, refined_candidate[0]["predicted_tree"], *scale_params[0])
  File "D:\xx\TPSR\timeout.py", line 16, in wrapper
    signal.signal(signal.SIGALRM, _handle_timeout)
AttributeError: module 'signal' has no attribute 'SIGALRM'
```

I would need assistance with fixing an error. Can you please guide me on how to resolve this issue?

**Comment by parshinsh** [comment]
Hi @Ohay-Angah ,

Thank you for your interest in TPSR!

It seems like the AttributeError you're encountering is related to the `signal.SIGALRM` attribute, which is not available on Windows platforms. If you're using Windows, this could be the cause of the problem. I couldn't replicate this error on the Unix-based system.

If the operating system is Windows, probably need to consider an alternative approach like `multithreading`  to create a similar effect. If you have access to a Unix-based system, try running the script there and let us know if the issue persists.

**Comment by Ohay-Angah** [comment]
It works on Unix-based systems like a charm. I can also run your code on Windows if commenting `timeout(10)` property on the top of `rescale_function`.

How do you understand the eval_results, 'cause running the symbolicregression skeleton seems to give me very different expression outcomes from the expectations?
```
python run.py --eval_mcts_on_pmlb True \
                   --pmlb_data_type feynman \
                   --target_noise 0.0 \
                   --lam 0.1 \
                   --horizon 200 \
                   --width 3 \
                   --num_beams 1 \
                   --rollout 3 \
                   --no_seq_cache False \
                   --no_prefix_cache True \
                   --max_input_points 200 \
                   --max_number_bags 10 \
                   --save_results True
```

I put a snippet of my current results here.

![image](https://github.com/deep-symbolic-mathematics/TPSR/assets/66444739/bc257d8c-20a3-453e-88cc-8d01b7ed5cea)

**Comment by parshinsh** [comment]
@Ohay-Angah Happy to hear that!

TPSR is building on the Transformer symbolic regression models. As these models are pretrained with millions of synthetic math functions, their power is in learning strong priors for this task (numeric-to-symbolic mapping) rather than the exact recovery of expressions. We noticed that in most cases predicted expressions with pretrained priors are close to true expressions after simplification or can generalize well to OOD data which signifies that the learned mathematical relations might be good approximation of true math relations. I hope this helps!

**Comment by Ohay-Angah** [comment]
The explanation helps, @parshinsh! I close this issue as it's been resolved!
